// <auto-generated />
namespace Chat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ChatMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChatMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "202202250519010_ChatMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
